"""initial schema

Revision ID: d99694a06b31
Revises: 
Create Date: 2026-09-15 14:21:10.685744
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import backend.app.db


revision: str = 'd99694a06b31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector must exist before the face_encounters embedding column is
    # created. On SQLite there is no extension and the column is JSON text, so
    # this is skipped — the same migration runs on both backends.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('officer_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('payload', backend.app.db.JSONColumn(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_officer_id'), ['officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_record_hash'), ['record_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_log_sequence'), ['sequence'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('officer_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETE', 'FAILED', name='casestatus', native_enum=False, length=16), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_officer_id'), ['officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_verdict'), ['verdict'], unique=False)

    op.create_table('verification_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile', backend.app.db.JSONColumn(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_profiles_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_profiles_is_active'), ['is_active'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('extracted_fields', backend.app.db.JSONColumn(), nullable=False),
    sa.Column('bboxes', backend.app.db.JSONColumn(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_image_hash'), ['image_hash'], unique=False)

    op.create_table('face_encounters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('embedding', backend.app.db.EmbeddingColumn(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=True),
    sa.Column('doc_number', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_encounters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_encounters_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_encounters_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_encounters_doc_number'), ['doc_number'], unique=False)

    op.create_table('checks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.String(length=128), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('evidence', backend.app.db.JSONColumn(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checks_check_id'), ['check_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checks_check_type'), ['check_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_checks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checks_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_checks_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_checks_severity'), ['severity'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checks_severity'))
        batch_op.drop_index(batch_op.f('ix_checks_result'))
        batch_op.drop_index(batch_op.f('ix_checks_module'))
        batch_op.drop_index(batch_op.f('ix_checks_document_id'))
        batch_op.drop_index(batch_op.f('ix_checks_check_type'))
        batch_op.drop_index(batch_op.f('ix_checks_check_id'))

    op.drop_table('checks')
    with op.batch_alter_table('face_encounters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_encounters_doc_number'))
        batch_op.drop_index(batch_op.f('ix_face_encounters_case_id'))
        batch_op.drop_index(batch_op.f('ix_face_encounters_captured_at'))

    op.drop_table('face_encounters')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_image_hash'))
        batch_op.drop_index(batch_op.f('ix_documents_doc_type'))
        batch_op.drop_index(batch_op.f('ix_documents_case_id'))

    op.drop_table('documents')
    with op.batch_alter_table('verification_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_profiles_is_active'))
        batch_op.drop_index(batch_op.f('ix_verification_profiles_doc_type'))

    op.drop_table('verification_profiles')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_verdict'))
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_officer_id'))
        batch_op.drop_index(batch_op.f('ix_cases_created_at'))

    op.drop_table('cases')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_sequence'))
        batch_op.drop_index(batch_op.f('ix_audit_log_record_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_log_officer_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_case_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
